name: ShiftLeft

on: [workflow_dispatch]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    container:
     image: shiftleft/scan
    steps:
    - run: scan --build
      
     
